CREATE TABLE IF NOT EXISTS emotions (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    anger NUMERIC(4,3),
    contempt NUMERIC(4,3),
    disgust NUMERIC(4,3),
    fear NUMERIC(4,3),
    happiness NUMERIC(4,3),
    neutral NUMERIC(4,3),
    sadness NUMERIC(4,3),
    surprise NUMERIC(4,3)
);